#!/usr/bin/env bash
# This script configures localhost to point to 127.0.0.2 and facebook.com to point to 8.8.8.8

# Delete localhost
sudo sed -i.bak '/127.0.0.1[[:space:]]*localhost/d' /etc/hosts

#add entries to /etc/hosts
{
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
} | sudo tee -a /etc/hosts > /dev/null

echo "Configuration updated successfully."
