#!/usr/bin/env bash

#backup the original /etc/hosts file
sudo cp /etc/hosts /etc/hosts.bak

#add entries to /etc/hosts
{
    echo "127.0.0.2 localhost"
    echo "8.8.8.8 facebook.com"
} | sudo tee -a /etc/hosts > /dev/null

echo "Configuration updated successfully."
